// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1yQHj5_dmmv9SNWTN5SXDVomJ-a3JcRI',
    appId: '1:696483916660:web:896f64c88c9f2c2b6f9a21',
    messagingSenderId: '696483916660',
    projectId: 'coinwirelive',
    authDomain: 'coinwirelive.firebaseapp.com',
    storageBucket: 'coinwirelive.appspot.com',
    measurementId: 'G-GTRTW7TRBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcjNSsrFsLkGdyeDXdl8ih64peoQ_35E',
    appId: '1:696483916660:android:a9270a01203c9cd76f9a21',
    messagingSenderId: '696483916660',
    projectId: 'coinwirelive',
    storageBucket: 'coinwirelive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3GU_VuXOHnL9UvO3ZYQpxqA7YgkXHuKo',
    appId: '1:696483916660:ios:bebf2f4c121e8acf6f9a21',
    messagingSenderId: '696483916660',
    projectId: 'coinwirelive',
    storageBucket: 'coinwirelive.appspot.com',
    iosClientId: '696483916660-7baap5gk4tcg8g0hfag69ssr6n87duee.apps.googleusercontent.com',
    iosBundleId: 'com.artasce.coinwirelive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3GU_VuXOHnL9UvO3ZYQpxqA7YgkXHuKo',
    appId: '1:696483916660:ios:bebf2f4c121e8acf6f9a21',
    messagingSenderId: '696483916660',
    projectId: 'coinwirelive',
    storageBucket: 'coinwirelive.appspot.com',
    iosClientId: '696483916660-7baap5gk4tcg8g0hfag69ssr6n87duee.apps.googleusercontent.com',
    iosBundleId: 'com.artasce.coinwirelive',
  );
}
